name: POC_ToRunJmeterTest
on:
  workflow_dispatch:

Jobs:
 JmeterTest:
   runs-on: ubuntu-latest

   steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install JMeter
      - name: Install Apache JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          export PATH=$PATH:$(pwd)/apache-jmeter-5.5/bin

      # Step 3: Run JMeter test
      - name: Execute JMeter Test Plan
        run: jmeter -n -t ./Scripts/Gol_Launch.jmx -l results.jtl

      # Step 4: Save results as artifact
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
          retention-days: 7
    
