name: POC_ToRunJmeterTest
on:
  workflow_dispatch:

jobs:
 JmeterTest:
   runs-on: ubuntu-latest

   steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install JMeter
      - name: Install Apache JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          export PATH=$PATH:$(pwd)/apache-jmeter-5.5/bin

      # Step 2.1: Verify Jmeter Installation
      - name: Check PATH
        run: echo $PATH
        
      - name: Check JMeter Installation
        run: ./apache-jmeter-5.5/bin/jmeter -v

      # Step 2.2: Verify the script path
      - name: List files
        run: ls -R

      # Step 2.3: Verify the working Directory
      - name: working directory
        run: pwd

      # Step 3: Run JMeter test
      - name: Execute JMeter Test Plan
        run: jmeter -n -t ./Scripts/Gol_Launch.jmx -l results.jtl

      # Step 4: Save results as artifact
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
          retention-days: 7
    
