name: POC_ToRunJmeterTest
on:
  workflow_dispatch:

jobs:
 JmeterTest:
   runs-on: ubuntu-latest

   steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2.3: Verify the working Directory
      - name: working directory
        run: pwd

      # Install JMeter
      - name: Install Apache JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          echo "PATH=$PATH:$(pwd)/apache-jmeter-5.5/bin" >> $GITHUB_ENV

      # Verify Jmeter Path
      - name: Check PATH
        run: echo $PATH

      # Install JMeter Plugins Manager
      - name: Install JMeter Plugins Manager
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar -O jmeter-plugins-manager.jar
          mv jmeter-plugins-manager.jar apache-jmeter-5.5/lib/ext/

      # Verify Plugin Installation
      - name: Verify Plugin Installation
        run: ls apache-jmeter-5.5/lib/ext/jmeter-plugins-manager.jar

      # Verify JMeter Installation
      - name: Verify JMeter Installation
        run: jmeter -v

      # List Jmeter files
      - name: List Jmeter files
        run: ls -R

      # Verify PluginsManagerCMD
      - name: Verify PluginsManagerCMD
        run: |
          ./apache-jmeter-5.5/bin/PluginsManagerCMD.sh status
          ls apache-jmeter-5.5/bin/PluginsManagerCMD.sh

      # Install BlazeMeter Plugin
      - name: Install BlazeMeter Plugin
        run:  ./apache-jmeter-5.5/bin/PluginsManagerCMD.sh install bzm-parallel

      # Step 3: Run JMeter test
      - name: Execute JMeter Test Plan
        run: jmeter -n -t ./Scripts/Gol_Launch.jmx -l results.jtl

      # Step 4: Save results as artifact
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
          retention-days: 7
    
