name: POC_ToRunJmeterTest
on:
  workflow_dispatch:

jobs:
 JmeterTest:
   runs-on: ubuntu-latest

   steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2.3: Verify the working Directory
      - name: working directory
        run: pwd

      # Step 1: Print Docker Version
      - name: Check Docker Version
        run: docker --version

      # Step 2: Verify Docker Service
      - name: Check Docker Status
        run: |
          sudo systemctl status docker

      - name: Verify Java Version
        run: java -version

      # Step 2: Pull Docker Image for JMeter
      - name: Pull JMeter Docker Image
        run: docker pull justb4/jmeter:latest

      # Verify JMeter Installation
      - name: Verify JMeter Installation
        run: jmeter -v

      # List Jmeter files
      - name: List Jmeter files
        run: ls -R

      # Step 3: Run JMeter Test
      - name: Execute JMeter Test
        run: |
          docker run --rm \
          -v $(pwd):/jmeter \
          justb4/jmeter:latest \
          -n -t /jmeter/Scripts/Gol_Launch_2.jmx  -l /jmeter/results.jtl -e -o /jmeter/report

      # Step 4: Save results as artifact
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
          retention-days: 7
    
