name: POC_ToRunJmeterTest
on:
  workflow_dispatch:

jobs:
 JmeterTest:
   runs-on: ubuntu-latest

   steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2.3: Verify the working Directory
      - name: working directory
        run: pwd

      - name: Verify Java Version
        run: java -version

      - name: Execute JMeter Test
        run: |
          docker run --rm \
          -v $(pwd):/jmeter \
          blazemeter/jmeter:latest \
          -n -t /jmeter/script/Gol_Launch_2.jmx -l /jmeter/results.jtl -e -o /jmeter/report

      # Step 4: Save results as artifact
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: report/
          retention-days: 7
    
